---
title: Defund12.org
timezone: UTC
collections:
  emails:
    title: Emails
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
subtitle: Follow the links below to email government officials and council members
  to reallocate egregious police budgets towards education, social services, and dismantling
  racial inequality.
meta: Email government officials and council members to reallocate police budgets
  towards education, social services, and dismantling racial inequality.
footer_text: 'Want to add your city? [Open a request.](https://github.com/teddywilson/defund12.org/issues)
  We are currently handling a lot of requests - please include the following information
  with your request: a list of emails (at least one) for the government officials
  you''d like to receive the message, and a detailed message concerning the budgeting
  decisions that are at stake in your community. See our current links for examples.'
