---
title: Defund12.org
timezone: UTC
collections:
  emails:
    title: Emails
    output: true
    city:
      city: 
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: emails
  values:
    layout: email
    name: 
    city: 
    state: 
permalink: pretty
subtitle: Email government officials and council members to reallocate egregious police
  budgets towards education, social services, and dismantling racial inequality.
meta: Email government officials and council members to reallocate police budgets
  towards education, social services, and dismantling racial inequality.
footer_text: Want to add your city? [Open a request.](https://github.com/teddywilson/defund12.org/issues)
email_intro_text: |-
  This page automatically opens a drafted email for you.

  Didn't work correctly? You can copy and paste the recipients, subject and message individually below.
