---
title: Defund12.org
subtitle: |
  Follow the links below to email government officials and council members to reallocate egregious 
  police budgets towards education, social services, and dismantling racial inequality.
timezone: America/New_York
collections:
  emails:
    title: Emails
    output: true
url: http://defund12.org
sass:
  style: compressed
